### ISSUE TITLE
Reloading arena doesn't work.

### ISSUE THREAD

**Issue by UnclassifiedX** [UnclassifiedX/Colormatch#4]
Typing 'done' during setup does not reload the arena and requires a server reboot.

**Comment by UnclassifiedX** [comment]
Update: With the methods currently in place, by reloading the data it creates another instance all together messing up the plugin. The function for reloading arenas with new data should follow with a prompt telling the player to reboot the server to see the changes.

**Comment by Wabit02** [comment]
how to reebot?
